
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[447] =
    {   0,
       54,   54,   66,   64,   65,   58,   64,   65,   57,   58,
       65,   37,   64,   65,   53,   64,   65,   27,   64,   65,
       64,   65,   43,   64,   65,   44,   64,   65,   25,   64,
       65,   23,   64,   65,   39,   64,   65,   24,   64,   65,
       40,   64,   65,   26,   64,   65,   51,   64,   65,   51,
       64,   65,   38,   64,   65,   28,   64,   65,   32,   64,
       65,   30,   64,   65,   49,   64,   65,16434,   49,   64,
       65,16434,   49,   64,   65,16434,   49,   64,   65,16434,
       41,   64,   65,   42,   64,   65,   49,   64,   65,16434,
       49,   64,   65,16434,   49,   64,   65,16434,   49,   64,

       65,16434,   49,   64,   65,16434,   49,   64,   65,16434,
       49,   64,   65,16434,   49,   64,   65,16434,   49,   64,
       65,16434,   49,   64,   65,16434,   49,   64,   65,16434,
       49,   64,   65,16434,   45,   64,   65,   64,   65,   46,
       64,   65,   54,   65,   55,   65,   56,   65,   62,   65,
       63,   65,   62,   65,   34,   35,   60,   52,   51,   29,
       33,   31,   49,16434,   49,16434,   49,16434,   49,16434,
       49,16434,   49,16434,   49,16434,   49,16434,   49,16434,
       49,16434,   49,16434,   49,16434,   14,   49,16434,   49,
    16434,   49,16434,   49,16434,   49,16434,   49,16434,   49,

    16434,   49,16434,   49,16434,   49,16434,   36,   54,   61,
       59,   52,   51,   51,   51, 8242,   18,   49,16434,   49,
    16434,   49,16434,   49,16434,   49,16434,   49,16434,   49,
    16434,   49,16434,   49,16434,   49,16434,   12,   49,16434,
       49,16434,    2,   49,16434,   49,16434,   49,16434,   49,
    16434,   49,16434,   49,16434,   49,16434,   49,16434,   52,
       49,16434,   49,16434,   49,16434,    4,   49,16434,   49,
    16434,   49,16434,   49,16434,   15,   49,16434,   49,16434,
       49,16434,   14, 8242,   49,16434,   49,16434,    8,   49,
    16434,   49,16434,   49,16434,    9,   49,16434,   47,   49,

    16434,    1,   49,16434,   49,16434,   18, 8242,   49,16434,
       20,   49,16434,   49,16434,   49,16434,   17,   49,16434,
        6,   49,16434,   49,16434,   49,16434,   48,   49,16434,
       12, 8242,   49,16434,    2, 8242,   49,16434,   49,16434,
       49,16434,   13,   49,16434,   49,16434,   49,16434,   49,
    16434,    4, 8242,    3,   49,16434,   15, 8242,   49,16434,
       49,16434,   49,16434,    8, 8242,   16,   49,16434,    5,
       49,16434,    9, 8242,   47, 8242,    1, 8242,   49,16434,
       20, 8242,   49,16434,   49,16434,   17, 8242,    6, 8242,
       10,   49,16434,   48, 8242,   49,16434,   49,16434,   13,

     8242,   19,   49,16434,   49,16434,   22,   49,16434,    3,
     8242,   49,16434,   49,16434,   16, 8242,    5, 8242,   49,
    16434,   10, 8242,   49,16434,    7,   49,16434,   19, 8242,
       49,16434,   22, 8242,   11,   49,16434,   21,   49,16434,
        7, 8242,   11, 8242,   21, 8242
    } ;

static yyconst flex_int16_t yy_accept[281] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    4,    6,    9,
       12,   15,   18,   21,   23,   26,   29,   32,   35,   38,
       41,   44,   47,   50,   53,   56,   59,   62,   65,   69,
       73,   77,   81,   84,   87,   91,   95,   99,  103,  107,
      111,  115,  119,  123,  127,  131,  135,  138,  140,  143,
      145,  147,  149,  151,  153,  155,  156,  157,  158,  158,
      159,  160,  160,  161,  162,  163,  163,  165,  165,  167,
      169,  171,  173,  175,  177,  179,  181,  183,  185,  187,
      190,  192,  194,  196,  198,  200,  202,  204,  206,  208,
      209,  210,  211,  211,  212,  213,  213,  214,  215,  216,

      217,  217,  220,  222,  224,  226,  228,  230,  232,  234,
      236,  238,  241,  241,  241,  243,  246,  248,  250,  252,
      254,  256,  258,  260,  260,  261,  261,  263,  263,  265,
      267,  270,  272,  274,  276,  279,  281,  283,  283,  283,
      285,  285,  287,  287,  287,  289,  292,  294,  296,  299,
      302,  305,  307,  309,  311,  311,  314,  316,  318,  318,
      318,  321,  324,  326,  326,  326,  328,  331,  333,  333,
      335,  337,  337,  339,  339,  339,  341,  343,  343,  343,
      343,  343,  343,  343,  346,  348,  348,  348,  350,  352,
      354,  354,  354,  354,  354,  354,  357,  359,  359,  361,

      361,  361,  363,  365,  367,  367,  370,  373,  375,  375,
      377,  377,  379,  379,  379,  379,  381,  383,  383,  385,
      387,  389,  389,  391,  391,  391,  391,  394,  396,  396,
      398,  400,  400,  400,  400,  400,  402,  402,  405,  407,
      410,  412,  412,  412,  412,  414,  416,  418,  418,  420,
      420,  420,  420,  422,  422,  422,  424,  424,  426,  429,
      431,  431,  433,  435,  435,  438,  438,  438,  441,  441,
      441,  443,  443,  443,  443,  445,  445,  447,  447,  447
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   23,   23,   23,   24,   23,
       25,   25,   26,   25,   25,   27,   25,   28,   25,   29,
       25,   30,   25,   25,   25,   25,   25,   31,   25,   25,
       32,    1,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   25,   44,   45,   46,   47,
       48,   49,   25,   50,   51,   52,   53,   54,   55,   56,
       57,   25,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[61] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    5,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[310] =
    {   0,
        0,    0,   58,   59,   62,   63,  120, 1035, 1035, 1035,
       97, 1035, 1035,  105, 1035, 1035, 1035, 1035, 1035, 1035,
     1035,   59,   54,   61, 1035,   88,   85,   78,   77,   79,
       81,   84, 1035, 1035,   87,   89,   92,   94,   97,  101,
      104,  112,  140,  151,  156,  153, 1035,   34, 1035,    0,
     1035, 1035, 1035, 1035,   73, 1035, 1035, 1035,   73,  145,
      111,  189, 1035, 1035, 1035,  162,  164,  174,  168,  171,
      184,  188,  176,  207,  215,  219,  228,  230,  232,  235,
      241,  246,  251,  253,  256,  269,  263,  289,  291, 1035,
        0, 1035,   64, 1035,  260,  291,    0,  302,  311, 1035,

      284,  307,  311,  328,  333,  335,  339,  350,  342,  352,
      360,  366,  370,  354,  373,  377,  391,  393,  397,  401,
      405,  410,  417,   85,  164,  419,  424,  412,  428,  432,
      436,  451,  464,  467,  469,  473,  475,  479,  483, 1035,
      485,  487,  489,  491,  495,  500,  506,  520,  526,  528,
      531,  533, 1035,  537,  540,  544,  546,  548,  551,  559,
      568,  572,  579,  582,  586,  592,  594, 1035,  596,  599,
     1035,  603,  606,  610,  614,  618,  620,  625,  630,  632,
      637,  641,  646,  651,  653,  657,  664,  666,  669, 1035,
      672,  674,  678,  688,  684,  690, 1035,  692,  697,  700,

      705,  707,  710, 1035,  721,  712,  724, 1035,  728, 1035,
      731, 1035,  733,  738,  747,  749, 1035,  755,  757,  760,
     1035,  765, 1035,  769,  771,  774,  776, 1035,  780,  782,
      784,  788,  791,  798,  802, 1035,  807,  809,  815,  820,
     1035,  824,  829,  831,  834,  836, 1035,  840, 1035,  843,
      846,  848,  851,  856,  860, 1035,  867,  869,  877, 1035,
      882,  889, 1035,  892,  894,  896,  900,  902,  904,  908,
     1035,  910,  914,  916, 1035,  920, 1035,  927, 1035,  960,
      965,  969,  974,  979,  983,  985,  987,  989,  991,  993,
      995,  997,  999, 1001, 1003, 1005, 1007, 1009, 1011, 1013,

     1015, 1017, 1019, 1021, 1023, 1025, 1027, 1029, 1031
    } ;

static yyconst flex_int16_t yy_def[310] =
    {   0,
      279,    1,  280,  280,  281,  281,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  282,  282,
      282,  282,  279,  279,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  279,  279,  279,  283,
      279,  279,  279,  279,  279,  279,  279,  279,  284,  279,
      279,  279,  279,  279,  279,  285,  282,  279,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  282,  282,  279,
      283,  279,  284,  279,  279,  279,   62,  279,  279,  279,

      279,  282,  282,  282,  282,  282,  282,  282,  282,  282,
      282,  282,  286,  279,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  279,  279,  287,  282,  279,  282,  282,
      282,  282,  282,  282,  282,  282,  282,  288,  279,  279,
      279,  282,  289,  279,  282,  282,  282,  282,  282,  282,
      282,  282,  279,  282,  279,  282,  282,  282,  290,  279,
      282,  282,  282,  291,  279,  282,  282,  279,  279,  282,
      279,  279,  282,  292,  279,  282,  282,  293,  279,  294,
      279,  295,  279,  282,  282,  296,  279,  282,  282,  279,
      279,  297,  279,  298,  279,  282,  279,  279,  282,  299,

      279,  282,  282,  279,  279,  282,  282,  279,  279,  279,
      279,  279,  279,  300,  279,  282,  279,  279,  282,  282,
      279,  279,  279,  279,  301,  279,  282,  279,  279,  282,
      282,  302,  279,  303,  279,  279,  279,  282,  282,  282,
      279,  279,  304,  279,  282,  282,  279,  279,  279,  279,
      305,  279,  282,  306,  279,  279,  279,  282,  282,  279,
      279,  282,  279,  279,  282,  307,  279,  282,  308,  279,
      279,  279,  309,  279,  279,  279,  279,  279,    0,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279
    } ;

static yyconst flex_int16_t yy_nxt[1096] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   29,   29,   29,   29,   29,   30,   31,   32,
       29,   33,   34,    8,   29,   35,   36,   37,   38,   39,
       29,   29,   40,   29,   29,   29,   41,   29,   29,   42,
       43,   44,   29,   45,   46,   29,   29,   47,   48,   49,
       51,   51,   52,   52,   54,   54,   94,   60,   58,   61,
       61,   55,   55,   59,   60,   94,   61,   61,   66,   66,
       66,   66,   66,   66,   62,   66,   66,   92,   66,   66,
       66,   66,   90,   66,   66,   66,   66,   65,   66,   66,

      125,  125,   66,   66,   64,   66,   66,   63,   68,   62,
       68,   57,   68,   66,   66,   68,   56,   69,   68,  279,
       68,  279,   71,   68,   60,   68,   61,   61,   68,  279,
       70,   78,   68,   74,   72,   68,   73,  279,   76,   75,
       80,   66,   66,   68,   79,  279,   81,   82,  279,   77,
       84,  279,   66,   66,   66,   66,   83,   66,   66,  279,
       95,   95,  279,   66,   66,   66,   66,  279,   96,   66,
       66,   68,   66,   66,  279,  101,  101,   66,   66,  125,
      125,  279,   68,   96,   68,   66,   66,   68,  279,   66,
       66,   85,   86,   68,   89,   68,  279,  279,  279,   68,

       87,  279,   68,   88,   97,   97,  100,   68,   66,   66,
       98,   98,   98,  103,  106,   68,   66,   66,  104,   68,
       66,   66,  102,   99,   99,   99,   99,   99,   99,   66,
       66,   66,   66,   66,   66,  105,  113,  113,   68,  279,
      279,  107,   66,   66,  279,  279,   68,   66,   66,  279,
       68,  279,   66,   66,   66,   66,  279,   66,   66,   68,
      279,   68,  279,   68,   66,   66,  114,  108,  279,  109,
       66,   66,   68,  279,  111,   95,   95,   68,  279,  110,
      279,  112,   68,   96,   68,  101,  101,   68,  279,  115,
       66,   66,   66,   66,   68,  117,  279,  116,   96,  279,

       68,  124,  279,  124,  118,  119,  125,  125,  126,  126,
      279,  120,   66,   66,  279,  121,  100,   98,   98,  279,
       68,  279,   68,   98,   98,   98,   99,   99,  127,   66,
       66,  122,  279,  123,   66,   66,   66,   66,  128,  279,
       66,   66,   68,   66,   66,   99,   99,   99,   99,   99,
       99,   66,   66,   66,   66,  141,  141,  129,  279,   68,
      279,   66,   66,  279,   68,  130,   68,  138,  138,  132,
       68,  113,  113,   68,   66,   66,  279,  131,  143,  143,
      135,   68,  279,   68,  279,  134,  140,  279,  279,  133,
      136,   68,   66,   66,   66,   66,  279,  139,   66,   66,

      279,  114,   66,   66,   68,  279,   66,   66,  144,  279,
      137,   66,   66,  155,  155,  145,  279,  142,   66,   66,
      126,  126,   68,  279,   68,   66,   66,  279,   68,   66,
       66,  279,   68,   66,   66,  146,   68,  159,  159,  148,
      279,   68,  279,  150,  153,  147,  279,  151,   68,  279,
      128,  149,   66,   66,  279,   68,  279,  157,  158,   68,
      279,  152,  279,   68,  279,   66,   66,  160,   66,   66,
      164,  164,  279,  154,   66,   66,   66,   66,  279,  156,
      138,  138,   68,  279,  169,  169,  141,  141,   66,   66,
      143,  143,  172,  172,  161,   68,   66,   66,   68,  279,

      165,  174,  174,  279,   68,  279,   68,   66,   66,  279,
      139,  163,  279,  167,  162,  168,  279,  140,   68,  166,
      144,   66,   66,  171,  279,  170,   68,  178,  178,  180,
      180,  175,  182,  182,   66,   66,  279,   68,   66,   66,
      279,  155,  155,  279,  173,  186,  186,   66,   66,   66,
       66,   68,  159,  159,  279,  176,  279,  179,  279,  181,
      191,  191,  183,  279,   68,  279,  177,  279,   68,  192,
      192,  184,  153,  194,  194,  187,  279,   68,  279,   68,
       66,   66,  160,  164,  164,  279,  185,  198,  198,  279,
      189,  190,  188,   66,   66,  200,  200,  169,  169,  193,

       66,   66,  279,  195,  172,  172,  279,   66,   66,  279,
       68,  174,  174,  165,  279,  205,  205,  196,  197,   66,
       66,   66,   66,   68,  279,  201,  178,  178,  168,  199,
       68,  209,  209,  180,  180,  171,  279,   68,  211,  211,
      279,  175,  182,  182,  202,  203,  204,  213,  213,   68,
      279,   68,  214,  214,   66,   66,  179,  279,  186,  186,
      207,  279,  208,  181,  206,  218,  218,   66,   66,  210,
       66,   66,  183,  191,  191,  192,  192,  279,  212,  222,
      222,  279,  215,  279,   68,  224,  224,  216,  187,  194,
      194,  225,  225,  198,  198,  279,  217,   68,   66,   66,

       68,  200,  200,  279,  190,  193,  229,  229,   66,   66,
      221,   66,   66,  232,  232,  220,  223,  219,  279,  195,
      279,  226,  205,  205,  197,  234,  234,  279,   68,  209,
      209,  201,  211,  211,  213,  213,  279,  228,   68,  214,
      214,   68,  279,  233,  231,  230,  279,  227,  237,  237,
       66,   66,  279,  204,  279,  235,  218,  218,   66,   66,
      208,   66,   66,  210,  279,  212,  222,  222,  279,  215,
      224,  224,  225,  225,  279,  242,  242,  243,  243,  236,
       68,  229,  229,   66,   66,   66,   66,  217,   68,  232,
      232,   68,  248,  248,  279,  239,  279,  221,  240,  234,

      234,  223,  226,  250,  250,  238,  241,  244,  237,  237,
      251,  251,  228,   68,  279,   68,   66,   66,  279,  233,
      246,  254,  254,  247,  279,  242,  242,  279,  245,  235,
      243,  243,  257,  257,  249,   66,   66,   66,   66,  236,
      252,  248,  248,  279,  250,  250,   68,  251,  251,  261,
      261,  255,   66,   66,  279,  253,  241,  254,  254,  279,
      244,  264,  264,  256,  279,   68,  279,   68,  257,  257,
       66,   66,  247,  279,  259,  249,  279,  252,  266,  266,
      260,  279,   68,  261,  261,  258,  279,  255,  279,  262,
       66,   66,  263,  264,  264,  269,  269,  266,  266,  256,

       68,  272,  272,  273,  273,  269,  269,  279,  267,  276,
      276,  272,  272,  279,  260,  273,  273,  278,  278,  265,
       68,  276,  276,  279,  263,  270,  279,  267,  278,  278,
      279,  279,  271,  274,  279,  270,  279,  279,  268,  279,
      275,  279,  271,  279,  279,  274,  279,  279,  277,  279,
      279,  279,  275,  279,  279,  279,  279,  279,  279,  277,
       50,   50,   50,   50,   50,   53,   53,   53,   53,   53,
       67,   67,  279,   67,   91,   91,  279,  279,   91,   93,
       93,   93,   93,   93,  100,  100,  140,  140,  153,  153,
      168,  168,  171,  171,  190,  190,  197,  197,  204,  204,

      208,  208,  210,  210,  212,  212,  217,  217,  221,  221,
      223,  223,  228,  228,  236,  236,  241,  241,  247,  247,
      249,  249,  256,  256,  260,  260,  263,  263,  271,  271,
      275,  275,  277,  277,    7,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279

    } ;

static yyconst flex_int16_t yy_chk[1096] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,    5,    6,   93,   23,   22,   23,
       23,    5,    6,   22,   24,   59,   24,   24,   29,   29,
       30,   30,   31,   31,   23,   32,   32,   55,   35,   35,
       36,   36,   48,   37,   37,   38,   38,   28,   39,   39,

      124,  124,   40,   40,   27,   41,   41,   26,   29,   23,
       30,   14,   31,   42,   42,   32,   11,   30,   35,    7,
       36,    0,   32,   37,   61,   38,   61,   61,   39,    0,
       31,   39,   40,   36,   35,   41,   35,    0,   38,   37,
       40,   43,   43,   42,   39,    0,   40,   40,    0,   38,
       42,    0,   44,   44,   46,   46,   41,   45,   45,    0,
       60,   60,    0,   66,   66,   67,   67,    0,   60,   69,
       69,   43,   70,   70,    0,   68,   68,   73,   73,  125,
      125,    0,   44,   60,   46,   71,   71,   45,    0,   72,
       72,   43,   44,   66,   46,   67,    0,    0,    0,   69,

       44,    0,   70,   45,   62,   62,   68,   73,   74,   74,
       62,   62,   62,   70,   73,   71,   75,   75,   71,   72,
       76,   76,   69,   62,   62,   62,   62,   62,   62,   77,
       77,   78,   78,   79,   79,   72,   80,   80,   74,    0,
        0,   74,   81,   81,    0,    0,   75,   82,   82,    0,
       76,    0,   83,   83,   84,   84,    0,   85,   85,   77,
        0,   78,    0,   79,   87,   87,   80,   75,    0,   76,
       86,   86,   81,    0,   78,   95,   95,   82,    0,   77,
        0,   79,   83,   95,   84,  101,  101,   85,    0,   81,
       88,   88,   89,   89,   87,   83,    0,   82,   95,    0,

       86,   96,    0,   96,   84,   85,   96,   96,  102,  102,
        0,   86,  103,  103,    0,   87,  101,   98,   98,    0,
       88,    0,   89,   98,   98,   98,   99,   99,  102,  104,
      104,   88,    0,   89,  105,  105,  106,  106,  102,    0,
      107,  107,  103,  109,  109,   99,   99,   99,   99,   99,
       99,  108,  108,  110,  110,  114,  114,  103,    0,  104,
        0,  111,  111,    0,  105,  104,  106,  112,  112,  106,
      107,  113,  113,  109,  115,  115,    0,  105,  116,  116,
      109,  108,    0,  110,    0,  108,  114,    0,    0,  107,
      110,  111,  117,  117,  118,  118,    0,  112,  119,  119,

        0,  113,  120,  120,  115,    0,  121,  121,  116,    0,
      111,  122,  122,  128,  128,  116,    0,  115,  123,  123,
      126,  126,  117,    0,  118,  127,  127,    0,  119,  129,
      129,    0,  120,  130,  130,  117,  121,  131,  131,  119,
        0,  122,    0,  121,  128,  118,    0,  122,  123,    0,
      126,  120,  132,  132,    0,  127,    0,  130,  130,  129,
        0,  123,    0,  130,    0,  133,  133,  131,  134,  134,
      135,  135,    0,  127,  136,  136,  137,  137,    0,  129,
      138,  138,  132,    0,  139,  139,  141,  141,  142,  142,
      143,  143,  144,  144,  132,  133,  145,  145,  134,    0,

      135,  146,  146,    0,  136,    0,  137,  147,  147,    0,
      138,  134,    0,  137,  133,  139,    0,  141,  142,  136,
      143,  148,  148,  144,    0,  142,  145,  149,  149,  150,
      150,  146,  151,  151,  152,  152,    0,  147,  154,  154,
        0,  155,  155,    0,  145,  156,  156,  157,  157,  158,
      158,  148,  159,  159,    0,  147,    0,  149,    0,  150,
      160,  160,  151,    0,  152,    0,  148,    0,  154,  161,
      161,  152,  155,  162,  162,  156,    0,  157,    0,  158,
      163,  163,  159,  164,  164,    0,  154,  165,  165,    0,
      158,  160,  157,  166,  166,  167,  167,  169,  169,  161,

      170,  170,    0,  162,  172,  172,    0,  173,  173,    0,
      163,  174,  174,  164,    0,  175,  175,  163,  165,  176,
      176,  177,  177,  166,    0,  167,  178,  178,  169,  166,
      170,  179,  179,  180,  180,  172,    0,  173,  181,  181,
        0,  174,  182,  182,  170,  173,  175,  183,  183,  176,
        0,  177,  184,  184,  185,  185,  178,    0,  186,  186,
      177,    0,  179,  180,  176,  187,  187,  188,  188,  181,
      189,  189,  182,  191,  191,  192,  192,    0,  183,  193,
      193,    0,  184,    0,  185,  195,  195,  185,  186,  194,
      194,  196,  196,  198,  198,    0,  187,  188,  199,  199,

      189,  200,  200,    0,  191,  192,  201,  201,  202,  202,
      193,  203,  203,  206,  206,  189,  195,  188,    0,  194,
        0,  196,  205,  205,  198,  207,  207,    0,  199,  209,
      209,  200,  211,  211,  213,  213,    0,  201,  202,  214,
      214,  203,    0,  206,  203,  202,    0,  199,  215,  215,
      216,  216,    0,  205,    0,  207,  218,  218,  219,  219,
      209,  220,  220,  211,    0,  213,  222,  222,    0,  214,
      224,  224,  225,  225,    0,  226,  226,  227,  227,  215,
      216,  229,  229,  230,  230,  231,  231,  218,  219,  232,
      232,  220,  233,  233,    0,  219,    0,  222,  220,  234,

      234,  224,  225,  235,  235,  216,  226,  227,  237,  237,
      238,  238,  229,  230,    0,  231,  239,  239,    0,  232,
      231,  240,  240,  233,    0,  242,  242,    0,  230,  234,
      243,  243,  244,  244,  235,  245,  245,  246,  246,  237,
      238,  248,  248,    0,  250,  250,  239,  251,  251,  252,
      252,  240,  253,  253,    0,  239,  242,  254,  254,    0,
      243,  255,  255,  244,    0,  245,    0,  246,  257,  257,
      258,  258,  248,    0,  246,  250,    0,  251,  259,  259,
      252,    0,  253,  261,  261,  245,    0,  254,    0,  253,
      262,  262,  255,  264,  264,  265,  265,  266,  266,  257,

      258,  267,  267,  268,  268,  269,  269,    0,  259,  270,
      270,  272,  272,    0,  261,  273,  273,  274,  274,  258,
      262,  276,  276,    0,  264,  265,    0,  266,  278,  278,
        0,    0,  267,  268,    0,  269,    0,    0,  262,    0,
      270,    0,  272,    0,    0,  273,    0,    0,  274,    0,
        0,    0,  276,    0,    0,    0,    0,    0,    0,  278,
      280,  280,  280,  280,  280,  281,  281,  281,  281,  281,
      282,  282,    0,  282,  283,  283,    0,    0,  283,  284,
      284,  284,  284,  284,  285,  285,  286,  286,  287,  287,
      288,  288,  289,  289,  290,  290,  291,  291,  292,  292,

      293,  293,  294,  294,  295,  295,  296,  296,  297,  297,
      298,  298,  299,  299,  300,  300,  301,  301,  302,  302,
      303,  303,  304,  304,  305,  305,  306,  306,  307,  307,
      308,  308,  309,  309,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279

    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "decaf.lex"
/* definitions */
#line 4 "decaf.lex"

#include <iostream>

using namespace std;

#include "tokentype.h"

string resultString;
Token* myTok;
size_t addlines;

int error(string msg, int line)
{
  cout << msg << " on line " << line << endl;
  return -1;
}

TokenType makeToken(TokenType type) {
    myTok = new Token(type, yytext, yylineno);
    return type;
}




#line 882 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define MLC 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 33 "decaf.lex"


  /* keywords */

#line 1071 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 280 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1035 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 37 "decaf.lex"
{ return makeToken(T_Void); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 38 "decaf.lex"
{ return makeToken(T_Int); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 39 "decaf.lex"
{ return makeToken(T_Double); }
	YY_BREAK
case 4:
/* rule 4 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 40 "decaf.lex"
{ return makeToken(T_Bool); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 41 "decaf.lex"
{ return makeToken(T_String); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 42 "decaf.lex"
{ return makeToken(T_Class); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 9;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 43 "decaf.lex"
{ return makeToken(T_Interface); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 44 "decaf.lex"
{ return makeToken(T_Null); }
	YY_BREAK
case 9:
/* rule 9 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 45 "decaf.lex"
{ return makeToken(T_This); }
	YY_BREAK
case 10:
/* rule 10 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 46 "decaf.lex"
{ return makeToken(T_Extends); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 47 "decaf.lex"
{ return makeToken(T_Implements); }
	YY_BREAK
case 12:
/* rule 12 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 48 "decaf.lex"
{ return makeToken(T_For); }
	YY_BREAK
case 13:
/* rule 13 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 49 "decaf.lex"
{ return makeToken(T_While); }
	YY_BREAK
case 14:
/* rule 14 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 50 "decaf.lex"
{ return makeToken(T_If); }
	YY_BREAK
case 15:
/* rule 15 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 51 "decaf.lex"
{ return makeToken(T_Else); }
	YY_BREAK
case 16:
/* rule 16 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 52 "decaf.lex"
{ return makeToken(T_Return); }
	YY_BREAK
case 17:
/* rule 17 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 53 "decaf.lex"
{ return makeToken(T_Break); }
	YY_BREAK
case 18:
/* rule 18 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 54 "decaf.lex"
{ return makeToken(T_New); }
	YY_BREAK
case 19:
/* rule 19 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 55 "decaf.lex"
{ return makeToken(T_NewArray); }
	YY_BREAK
case 20:
/* rule 20 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 56 "decaf.lex"
{ return makeToken(T_Print); }
	YY_BREAK
case 21:
/* rule 21 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 11;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 57 "decaf.lex"
{ return makeToken(T_ReadInteger); }
	YY_BREAK
case 22:
/* rule 22 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 58 "decaf.lex"
{ return makeToken(T_ReadLine); }
	YY_BREAK
/* operations */
case 23:
YY_RULE_SETUP
#line 62 "decaf.lex"
{ return makeToken(T_Plus); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "decaf.lex"
{ return makeToken(T_Minus); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "decaf.lex"
{ return makeToken(T_Times); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "decaf.lex"
{ return makeToken(T_Div); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "decaf.lex"
{ return makeToken(T_Mod); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "decaf.lex"
{ return makeToken(T_Less); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "decaf.lex"
{ return makeToken(T_LessEqual); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "decaf.lex"
{ return makeToken(T_Greater); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "decaf.lex"
{ return makeToken(T_GreaterEqual); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "decaf.lex"
{ return makeToken(T_Assign); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "decaf.lex"
{ return makeToken(T_Equal); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "decaf.lex"
{ return makeToken(T_NotEqual); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "decaf.lex"
{ return makeToken(T_And); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "decaf.lex"
{ return makeToken(T_Or); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "decaf.lex"
{ return makeToken(T_Not); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "decaf.lex"
{ return makeToken(T_Semicolon); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "decaf.lex"
{ return makeToken(T_Comma); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "decaf.lex"
{ return makeToken(T_Dot); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "decaf.lex"
{ return makeToken(T_LBracket); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "decaf.lex"
{ return makeToken(T_RBracket); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "decaf.lex"
{ return makeToken(T_LParen); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "decaf.lex"
{ return makeToken(T_RParen); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 84 "decaf.lex"
{ return makeToken(T_LBrace); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "decaf.lex"
{ return makeToken(T_RBrace); }
	YY_BREAK
/* booleans */
case 47:
/* rule 47 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 88 "decaf.lex"
{ return makeToken(T_BoolConstant); }
	YY_BREAK
case 48:
/* rule 48 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 89 "decaf.lex"
{ return makeToken(T_BoolConstant); }
	YY_BREAK
/* identifier */
case 49:
YY_RULE_SETUP
#line 92 "decaf.lex"
{ string errmssg;
                        if (strlen(yytext) <= 31) return makeToken(T_Identifier);
                        else{
                            errmssg += "identifier ";
                            errmssg += yytext;
                            errmssg += " too long";
                            return error(errmssg, yylineno);
                        }; }
	YY_BREAK
/* type identifier */
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 102 "decaf.lex"
{ return makeToken(T_TypeIdentifier); }
	YY_BREAK
/* integer */
case 51:
YY_RULE_SETUP
#line 105 "decaf.lex"
{ return makeToken(T_IntConstant); }
	YY_BREAK
/* double literals */
case 52:
YY_RULE_SETUP
#line 108 "decaf.lex"
{ return makeToken(T_DoubleConstant); }
	YY_BREAK
/* string */
case 53:
YY_RULE_SETUP
#line 111 "decaf.lex"
{ BEGIN(STRING); resultString = "\""; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 112 "decaf.lex"
{ resultString += yytext; }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 113 "decaf.lex"
{return error("missing \" at end of string constant",
		yylineno); }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 115 "decaf.lex"
{return error("missing \" at end of string constant",
		yylineno); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 117 "decaf.lex"
{ BEGIN(INITIAL);
	         myTok = new Token(T_StringConstant,resultString + "\"",
                                  yylineno);
		 return T_StringConstant; }
	YY_BREAK
/* newline consumption */
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 123 "decaf.lex"
{ yylineno += 1; }
	YY_BREAK
/* whitespace */
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 126 "decaf.lex"
{}
	YY_BREAK
/* comments */
case 59:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 129 "decaf.lex"

	YY_BREAK
/* multi line comments */
case 60:
YY_RULE_SETUP
#line 132 "decaf.lex"
{ BEGIN(MLC); addlines = 0; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 133 "decaf.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 134 "decaf.lex"
{}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 135 "decaf.lex"
{ yylineno += 1; addlines += 1; }
	YY_BREAK
case YY_STATE_EOF(MLC):
#line 136 "decaf.lex"
{ return error("missing */ for block comment beginning on line", yylineno - addlines); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 138 "decaf.lex"
{ string errmsg;
     errmsg += "stray '";
     errmsg += yytext;
     errmsg += "'";
     return error(errmsg, yylineno); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 144 "decaf.lex"
{ return -1; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 146 "decaf.lex"
ECHO;
	YY_BREAK
#line 1651 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 280 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 280 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 279);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 146 "decaf.lex"



  /* subroutines */

int yywrap(void) {
    return 1;  // makes it stop at EOF.
    /* there's a warning without this */
    if (false)
        yyunput(0, 0);
}

